// Vitest Snapshot v1, https://vitest.dev/guide/snapshot.html

exports[`renderError > should handle nested cause errors 1`] = `
"Error: This is an error message

at <unknown> __tests__/error/render/error.test.ts:185

Caused by:

Error: This is the cause of the error
at <unknown> __tests__/error/render/error.test.ts:186

    Caused by:

    Error: This is the cause of the cause of the error
    at <unknown> __tests__/error/render/error.test.ts:187"
`;

exports[`renderError > should handle nested errors within AggregateError 1`] = `
"AggregateError

at <unknown> __tests__/error/render/error.test.ts:171

Errors:

    AggregateError

    at <unknown> __tests__/error/render/error.test.ts:169

    Errors:

        Error: Nested Error

        at <unknown> __tests__/error/render/error.test.ts:169"
`;

exports[`renderError > should respect base prefix option 1`] = `
"prefixError: This is an error message

prefixat <unknown> __tests__/error/render/error.test.ts:206

prefixCaused by:

prefixError: This is the cause of the error
prefixat <unknown> __tests__/error/render/error.test.ts:207

prefix    Caused by:

prefix    Error: This is the cause of the cause of the error
prefix    at <unknown> __tests__/error/render/error.test.ts:208"
`;
